### PR TITLE
Add filter for changing cpt_acf_page_args

### PR DESCRIPTION
**Pull request by saulirajala**
This pull requests adds filter for developer to use for changing arguments passed to `acf_add_options_page()`
This is handy at least for the following reasons:
- Changing the menu name. For example "Event Archive" is not always the most intuitive name for options page
- Better support with Polylang. If I have for example two languages registered to my site: English and Finnish. With defaults ACF-CPT-Options-Pages actually creates three options page for one post type: English, Finnish and all. "All" -option page is mostly not needed, so it would be a good idea to change it to default language. With the help of this filter, developer can do just that.

### CODE REVIEW

**Comment by Tusko** [comment]
@saulirajala Thank you for the request.
Your code worked with one CPT only.

I've edited that, and now you (we :D) can `add_filter` for each CPT :)

Please see the latest commit
https://github.com/Tusko/ACF-CPT-Options-Pages/commit/8a15f60a5dd00a10389e4a72d8f3062a3d1e6400

**Comment by saulirajala** [comment]
@Tusko Ah, yes. That is a better solution! Thank you!

Btw. Could you fix my name in readme? :)

**Comment by Tusko** [comment]
@saulirajala 
Sorry, I was so tired yesterday.
Fixed ;)

**Comment by saulirajala** [comment]
No problem! 👍

**Pull request merged**
